macro (do_test n m s r)
	add_test (Test${n} filter-it --input=${m} --filter=${s} --tab)
	set_tests_properties (Test${n} PROPERTIES PASS_REGULAR_EXPRESSION ${r})
endmacro (do_test)

do_test(1 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_1.txt "0.056")
do_test(2 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_2.txt "3")
do_test(3 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_3.txt "0")
do_test(4 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_4.txt "0.346")
do_test(5 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_5.txt "20.000")
do_test(6 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_6.txt "1")
do_test(7 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_7.txt "105.070")
do_test(8 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_8.txt "-6.879")
do_test(9 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_9.txt "5.279")
do_test(10 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_10.txt "476.748")
do_test(11 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_11.txt "0.034")
do_test(12 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_12.txt "1")
do_test(13 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_13.txt "1")
do_test(14 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_14.txt "1")
do_test(15 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_15.txt "0.586")
do_test(16 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_16.txt "17")
do_test(17 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_17.txt "1")
do_test(18 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_18.txt "0.414")
do_test(19 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_19.txt "7")
do_test(20 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_20.txt "1")
do_test(21 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_21.txt "4")
do_test(22 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_22.txt "2")
do_test(23 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_23.txt "1")
do_test(24 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_24.txt "0.552")
do_test(25 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_25.txt "10")
do_test(26 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_26.txt "6")
do_test(27 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_27.txt "2")
do_test(28 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_28.txt "0.000")
do_test(29 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_29.txt "0.000")
do_test(30 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_30.txt "0")
do_test(31 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_31.txt "32")
do_test(32 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_32.txt "0")
do_test(33 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_33.txt "1.000")
do_test(34 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_34.txt "0.552")
do_test(35 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_35.txt "6")
do_test(36 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_36.txt "6")
do_test(37 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_37.txt "3")
do_test(38 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_38.txt "0.552")
do_test(39 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_39.txt "6")
do_test(40 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_40.txt "6")
do_test(41 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_41.txt "3")
do_test(42 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_42.txt "0")
do_test(43 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_43.txt "2")
do_test(44 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_44.txt "4")
do_test(45 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_45.txt "5")
do_test(46 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_46.txt "4")
do_test(47 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_47.txt "4")
do_test(48 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_48.txt "2")
do_test(49 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_49.txt "1.000")
do_test(50 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_50.txt "0")
do_test(51 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_51.txt "7")
do_test(52 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_52.txt "31")
do_test(53 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_53.txt "0.242")
do_test(54 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_54.txt "2")
do_test(55 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_55.txt "0.318")
do_test(56 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_56.txt "7")
do_test(57 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_57.txt "22")
do_test(58 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_58.txt "29")
do_test(59 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_59.txt "C22H19BrClNO4")
do_test(60 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_60.txt "C22H19BrClNO4")
do_test(61 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_61.txt "OCCC[(]=O[)]C[(]c1cc[(]cc[(]c1[)]Cl[)]C[(]c1ccc[(]c2c1cccc2[)]Br[)]C[(]=O[)]")
do_test(61 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.smi ${PROJECT_SOURCE_DIR}/test/test_filter_62.txt "Warning: SIMILARITY_STACK filters are not run when in tabulate mode")
do_test(62 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_1.txt "0.032")
do_test(63 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_2.txt "3")
do_test(64 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_3.txt "0")
do_test(65 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_4.txt "0.346")
do_test(66 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_5.txt "20.000")
do_test(67 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_6.txt "1")
do_test(68 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_7.txt "105.070")
do_test(69 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_8.txt "-8.241")
do_test(70 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_9.txt "5.279")
do_test(71 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_10.txt "476.748")
do_test(72 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_11.txt "0.034")
do_test(73 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_12.txt "1")
do_test(74 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_13.txt "1")
do_test(75 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_14.txt "1")
do_test(76 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_15.txt "0.586")
do_test(77 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_16.txt "17")
do_test(78 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_17.txt "1")
do_test(79 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_18.txt "0.414")
do_test(80 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_19.txt "7")
do_test(81 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_20.txt "1")
do_test(82 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_21.txt "4")
do_test(83 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_22.txt "2")
do_test(84 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_23.txt "1")
do_test(85 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_24.txt "0.552")
do_test(86 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_25.txt "10")
do_test(87 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_26.txt "6")
do_test(88 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_27.txt "2")
do_test(89 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_28.txt "0.000")
do_test(90 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_29.txt "0.000")
do_test(91 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_30.txt "0")
do_test(92 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_31.txt "48")
do_test(93 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_32.txt "0")
do_test(94 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_33.txt "1.000")
do_test(95 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_34.txt "0.552")
do_test(96 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_35.txt "6")
do_test(97 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_36.txt "6")
do_test(98 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_37.txt "3")
do_test(99 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_38.txt "0.552")
do_test(100 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_39.txt "6")
do_test(101 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_40.txt "6")
do_test(102 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_41.txt "3")
do_test(103 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_42.txt "0")
do_test(104 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_43.txt "2")
do_test(105 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_44.txt "4")
do_test(106 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_45.txt "5")
do_test(107 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_46.txt "4")
do_test(108 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_47.txt "4")
do_test(109 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_48.txt "2")
do_test(110 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_49.txt "1.000")
do_test(111 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_50.txt "0")
do_test(112 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_51.txt "7")
do_test(113 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_52.txt "31")
do_test(114 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_53.txt "0.242")
do_test(115 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_54.txt "2")
do_test(116 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_55.txt "0.318")
do_test(117 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_56.txt "7")
do_test(118 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_57.txt "22")
do_test(119 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_58.txt "29")
do_test(120 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_59.txt "C22H19BrClNO4")
do_test(121 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_60.txt "C22H19BrClNO4")
do_test(122 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_61.txt "TEST_MOLECULE_1")
do_test(123 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_62.txt "Warning: SIMILARITY_STACK filters are not run when in tabulate mode")
do_test(124 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_63.txt "PATTERN filters are not run when in tabulate mode")
do_test(125 ${PROJECT_SOURCE_DIR}/test/test_molecule_1.sdf ${PROJECT_SOURCE_DIR}/test/test_filter_63.txt "Warning: DISTANCE filters are not run when in tabulate mode")

add_test (Test126 filter-it)
set_tests_properties (Test126 PROPERTIES PASS_REGULAR_EXPRESSION "Required '--input=.file.' option has not been given")
add_test (Test127 filter-it -h)
set_tests_properties (Test127 PROPERTIES PASS_REGULAR_EXPRESSION "Filter-it is a tool to filter molecules from molecules")
add_test (Test128 filter-it -v)
set_tests_properties (Test128 PROPERTIES PASS_REGULAR_EXPRESSION "Filter-it v1.0.")

